filter:
    excluded_paths:
        - Phrekyll/Vendor/*
        - tests/*
checks:
    php: true

build:
    environment:
        php: '5.6.16'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.out'
                coverage:
                    file: 'clover.out'
                    format: 'php-clover'