# Meta information about Phrekyll
---
name: Phrekyll
summary: Static web-site generator for PHP.
description: &desc Phrekyll is an extremely flexible static site generator for PHP.
version: &ver "0.9.0dev"
stability: beta
author: Paul Dixon

# executable customization
use_ansi_colors: false

command:
    name: /usr/bin/phrekyll
    description: *desc
    version: *ver
    add_help_option: false
    options:
        help:
            short_name:     -h
            long_name:      --help
            description:    Show this help message
            action:         StoreTrue
