# phr clobber
---
command:
    name: &name clobber
    aliases:
    description: &desc Purge Phrekyll project directory
    arguments:
        path:
            help_name: path
            description: Path to search Phrekyll directories in
            optional: true

# callback
callback: [Clobber, execute]

# documentation
docs:
    name: clobber
    summary: *desc
    description: |
        This command locates and removes Phrekyll project directory ".phrekyll", effectively
        deleting all user generated content.

        Use with caution.

        If output PATH not provided, current directory is assumed.
    usage: %bphrekyll%n %gclobber%n [PATH]
    examples: |
        To remove project directory in a current folder:
        %bphrekyll%n %gclobber%n

        To remove project directory in specified folder PATH:
        %bphrekyll%n %gclobber%n PATH
