# phr up
---
command:
    name: &name up
    aliases: [build, update]
    description: &desc Phrekyll usage manual
    options:
        regen:
            short_name:  -R
            long_name:   --regen
            doc_name:    -R [--regen]
            description: Re-generate the site from scratch removing any previous content
            action:      StoreTrue
    arguments:
        in:
            help_name: "[SRC]"
            description: Source directory
            optional: true
        out:
            help_name: "[DEST]"
            description: Destination directory
            optional: true

# callback
callback: [Up, execute]

# documentation
docs:
    name: update (up)
    summary: *desc
    description: |
        This command compiles/updates static site.

        If output PATH not provided, current directory is assumed.
    usage: %bphrekyll%n %gup%n [SRC] [DEST]
    examples: |
        To compile project in current directory:
        %bphrekyll%n %gup%n

        To compile project to specified directory DEST:
        %bphrekyll%n %ginit%n DEST

        To compile project located in current directory to directory DEST:
        %bphrekyll%n %ginit%n .
